name: Continuous Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write
  id-token: write

jobs:
  release-stable:
    name: Release Stable
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          title: 'chore(release): new version'
          commit: 'chore(release): new version'
          version: yarn changeset-version
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get current package version
        if: steps.changesets.outputs.published == 'true'
        id: get_version
        run: echo "CURRENT_PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Create Github Release
        if: steps.changesets.outputs.published == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.CURRENT_PACKAGE_VERSION }}

  release-unstable:
    name: Release Unstable (Alpha Snapshot)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create snapshot release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn changeset version --snapshot alpha
          yarn prettier --write .
          yarn build
          yarn changeset publish --tag alpha

          CURRENT_PACKAGE_VERSION=$(node -p "require('./package.json').version")

          git config --global user.name "Bhutan NDI"
          git config --global user.email "github@bhutanndi.bt"

          git tag v$CURRENT_PACKAGE_VERSION
          git push origin v$CURRENT_PACKAGE_VERSION --no-verify